# Generated by Django 2.2.12 on 2021-01-22 09:17

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_group', to='otree.Session')),
            ],
            options={
                'db_table': 'main_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'main_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('predict_1', otree.db.models.FloatField(null=True)),
                ('predict_2', otree.db.models.FloatField(null=True)),
                ('predict_3', otree.db.models.FloatField(null=True)),
                ('predict_4', otree.db.models.FloatField(null=True)),
                ('predict_5', otree.db.models.FloatField(null=True)),
                ('predict_6', otree.db.models.FloatField(null=True)),
                ('result', otree.db.models.FloatField(null=True)),
                ('information_score', otree.db.models.FloatField(null=True)),
                ('prediction_score', otree.db.models.FloatField(null=True)),
                ('bts', otree.db.models.FloatField(null=True)),
                ('top30', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('firstA', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('check_question', otree.db.models.BooleanField(choices=[[False, 'znižuje'], [True, 'zvyšuje'], [False, 'nemá vplyv na']], null=True, verbose_name='')),
                ('roll', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6']], default=0, null=True, verbose_name='Hodnota hodu:')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='Vek')),
                ('male', otree.db.models.BooleanField(choices=[[True, 'muž'], [False, 'žena']], null=True, verbose_name='Pohlavie')),
                ('nationality', otree.db.models.StringField(choices=[['svk', 'slovenská'], ['czk', 'česká'], ['other', 'iná']], max_length=10000, null=True, verbose_name='Národnosť')),
                ('faculty', otree.db.models.StringField(choices=[['LF', 'Lékařská fakulta '], ['FaF', 'Farmaceutická fakulta'], ['FF', 'Filozofická fakulta'], ['PrF', 'Právnická fakulta '], ['FSS', 'Fakulta sociálních studií '], ['PriF', 'Přírodovědecká fakulta '], ['FI', 'Fakulta informatiky '], ['PdF', 'Pedagogická fakulta '], ['FSpS', 'Fakulta sportovních studií'], ['ESF', 'Ekonomicko-správní fakulta ']], max_length=10000, null=True, verbose_name='Fakulta')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subsession')),
            ],
            options={
                'db_table': 'main_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subsession'),
        ),
    ]
