# Generated by Django 2.2.12 on 2021-02-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210128_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='check_question',
        ),
    ]
