# Generated by Django 2.2.12 on 2021-02-08 09:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_player_check_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='faculty',
            field=otree.db.models.StringField(choices=[['LF', 'Lékařská fakulta '], ['FaF', 'Farmaceutická fakulta'], ['FF', 'Filozofická fakulta'], ['PrF', 'Právnická fakulta '], ['FSS', 'Fakulta sociálních studií '], ['PriF', 'Přírodovědecká fakulta '], ['FI', 'Fakulta informatiky '], ['PdF', 'Pedagogická fakulta '], ['FSpS', 'Fakulta sportovních studií'], ['ESF', 'Ekonomicko-správní fakulta '], ['NoStudy', 'Nejsem student']], max_length=10000, null=True, verbose_name='Fakulta'),
        ),
        migrations.AlterField(
            model_name='player',
            name='male',
            field=otree.db.models.BooleanField(choices=[[True, 'muž'], [False, 'žena']], null=True, verbose_name='Pohlaví'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=otree.db.models.StringField(choices=[['svk', 'slovenská'], ['czk', 'česká'], ['other', 'iná']], max_length=10000, null=True, verbose_name='Národnost'),
        ),
    ]
