# Generated by Django 2.2.12 on 2021-02-08 09:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210208_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.IntegerField(null=True, verbose_name='Věk'),
        ),
    ]
