# Generated by Django 2.2.12 on 2021-02-11 11:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210209_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='faculty',
            field=otree.db.models.StringField(choices=[['LF', 'Lékařská fakulta '], ['FaF', 'Farmaceutická fakulta'], ['FF', 'Filozofická fakulta'], ['PrF', 'Právnická fakulta '], ['FSS', 'Fakulta sociálních studií '], ['PriF', 'Přírodovědecká fakulta '], ['FI', 'Fakulta informatiky '], ['PdF', 'Pedagogická fakulta '], ['FSpS', 'Fakulta sportovních studií'], ['ESF', 'Ekonomicko-správní fakulta '], ['NoStudy', 'Nejsem student'], ['OtherUni', 'jiná univerzita než MU']], max_length=10000, null=True, verbose_name='Fakulta'),
        ),
    ]
